# Generated by Django 5.0.7 on 2024-07-26 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazadanych', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='data_rejestracji',
            field=models.DateField(db_column='Date of Registry', null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='laboratorium',
            field=models.CharField(blank=True, db_column='Lab Name', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='system_operacyjny',
            field=models.ManyToManyField(blank=True, db_column='Operating System', to='bazadanych.operatingsystem'),
        ),
    ]
