# Generated by Django 5.0.7 on 2024-07-26 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bazadanych', '0002_alter_device_data_rejestracji_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OperatingSystem',
            new_name='SystemOperacyjny',
        ),
        migrations.RenameModel(
            old_name='Device',
            new_name='Urzadzenie',
        ),
        migrations.RenameModel(
            old_name='FormData',
            new_name='Zgloszenie',
        ),
    ]
