# Generated by Django 5.0.7 on 2024-07-29 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazadanych', '0003_rename_operatingsystem_systemoperacyjny_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urzadzenie',
            name='typ_polaczenia_sieciowego',
            field=models.CharField(blank=True, choices=[('Office', 'Office'), ('OT', 'OT'), ('Odizolowany', 'Odizolowany'), ('Brak', 'Brak')], db_column='Terminal Connection Type', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='urzadzenie',
            name='typ_urzadzenia',
            field=models.CharField(blank=True, choices=[('PC', 'PC'), ('Laptop', 'Laptop'), ('Monitor', 'Monitor'), ('Klimatyzator', 'Klimatyzator'), ('Inne', 'Inne')], db_column='Device Type', max_length=40, null=True),
        ),
    ]
