# Generated by Django 5.0.7 on 2024-07-29 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazadanych', '0004_alter_urzadzenie_typ_polaczenia_sieciowego_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urzadzenie',
            name='typ_polaczenia_sieciowego',
            field=models.CharField(blank=True, choices=[('Office', 'Office'), ('OT', 'OT'), ('Odizolowane', 'Odizolowane'), ('Brak', 'Brak')], db_column='Terminal Connection Type', max_length=40, null=True),
        ),
    ]
