# Generated by Django 5.0.7 on 2024-07-29 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazadanych', '0005_alter_urzadzenie_typ_polaczenia_sieciowego'),
    ]

    operations = [
        migrations.AddField(
            model_name='zgloszenie',
            name='urzadzenie_id',
            field=models.ForeignKey(blank=True, db_column='PIM ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='bazadanych.urzadzenie'),
        ),
    ]
