# Generated by Django 5.0.7 on 2024-07-29 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazadanych', '0006_zgloszenie_urzadzenie_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='urzadzenie',
            name='notatki',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zgloszenie',
            name='notatki',
            field=models.TextField(blank=True, null=True),
        ),
    ]
