# Generated by Django 5.0.7 on 2024-07-30 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bazadanych', '0007_urzadzenie_notatki_zgloszenie_notatki'),
    ]

    operations = [
        migrations.RenameField(
            model_name='systemoperacyjny',
            old_name='os_type',
            new_name='typ_system_operacyjny',
        ),
    ]
