# Generated by Django 5.0.7 on 2024-07-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nr_EZD_ID_koszulki', models.CharField(blank=True, max_length=100, null=True)),
                ('nr_zgloszenia', models.CharField(blank=True, max_length=100, null=True)),
                ('nr_EZD', models.CharField(blank=True, max_length=100, null=True)),
                ('data_zgloszenia', models.DateField(blank=True, null=True)),
                ('nazwa_zakladu', models.CharField(blank=True, choices=[('Zakład Badań Certyfikacyjnych (Z1)', 'Zakład Badań Certyfikacyjnych (Z1)'), ('Zakład Chemii Fizycznej i Środowiska (Z2)', 'Zakład Chemii Fizycznej i Środowiska (Z2)'), ('Zakład Czasu i Długości (Z3)', 'Zakład Czasu i Długości (Z3)'), ('Zakład Elektryczności i Promieniowania (Z4)', 'Zakład Elektryczności i Promieniowania (Z4)'), ('Zakład Mechaniki i Akustyki (Z5)', 'Zakład Mechaniki i Akustyki (Z5)'), ('Zakład Technologii Cyfrowych (Z6)', 'Zakład Technologii Cyfrowych (Z6)')], max_length=200, null=True)),
                ('laboratorium', models.CharField(blank=True, choices=[('Laboratorium Bezpieczeństwa Ruchu Drogowego (Z11)', 'Laboratorium Bezpieczeństwa Ruchu Drogowego (Z11)'), ('Laboratorium Badań Oprogramowania (Z12)', 'Laboratorium Badań Oprogramowania (Z12)'), ('Laboratorium Temperatury (Z21)', 'Laboratorium Temperatury (Z21)'), ('Laboratorium Wilgotności (Z22)', 'Laboratorium Wilgotności (Z22)'), ('Laboratorium Analizy Gazów (Z23)', 'Laboratorium Analizy Gazów (Z23)'), ('Laboratorium Analiz Elektrochemicznych i Nieorganicznych (Z24)', 'Laboratorium Analiz Elektrochemicznych i Nieorganicznych (Z24)'), ('Laboratorium Wzorców Fizykochemicznych (Z25)', 'Laboratorium Wzorców Fizykochemicznych (Z25)'), ('Laboratorium Czasu i Częstotliwości (Z31)', 'Laboratorium Czasu i Częstotliwości (Z31)'), ('Laboratorium Długości (Z32)', 'Laboratorium Długości (Z32)'), ('Laboratorium Precyzyjnych Pomiarów Geometrycznych (Z33)', 'Laboratorium Precyzyjnych Pomiarów Geometrycznych (Z33)'), ('Laboratorium Twardości (Z34)', 'Laboratorium Twardości (Z34)'), ('Laboratorium Nowych Technologii Czasu i Długości (Z35)', 'Laboratorium Nowych Technologii Czasu i Długości (Z35)'), ('Laboratorium Wzorców Wielkości Elektrycznych DC (Z41)', 'Laboratorium Wzorców Wielkości Elektrycznych DC (Z41)'), ('Laboratorium Wzorców Wielkości Elektrycznych Małej Częstotliwości (Z42)', 'Laboratorium Wzorców Wielkości Elektrycznych Małej Częstotliwości (Z42)'), ('Laboratorium Pomiarów Elektroenergetycznych (Z43)', 'Laboratorium Pomiarów Elektroenergetycznych (Z43)'), ('Laboratorium Mikrofal, Pola Elektromagnetycznego i Kompatybilności Elektromagnetycznej (Z44)', 'Laboratorium Mikrofal, Pola Elektromagnetycznego i Kompatybilności Elektromagnetycznej (Z44)'), ('Laboratorium Wzorców Spektrofotometrycznych (Z45)', 'Laboratorium Wzorców Spektrofotometrycznych (Z45)'), ('Laboratorium Wzorców Fotometrycznych i Radiometrycznych (Z46)', 'Laboratorium Wzorców Fotometrycznych i Radiometrycznych (Z46)'), ('Wieloosobowe Stanowisko Pracy do spraw Wzorców Barwy (Z47)', 'Wieloosobowe Stanowisko Pracy do spraw Wzorców Barwy (Z47)'), ('Laboratorium Promieniowania Jonizującego (Z48)', 'Laboratorium Promieniowania Jonizującego (Z48)'), ('Laboratorium Masy (Z51)', 'Laboratorium Masy (Z51)'), ('Laboratorium Przepływów (Z53)', 'Laboratorium Przepływów (Z53)'), ('Laboratorium Akustyki (Z55)', 'Laboratorium Akustyki (Z55)'), ('Laboratorium Drgań Mechanicznych (Z56)', 'Laboratorium Drgań Mechanicznych (Z56)'), ('Wieloosobowe Stanowisko Pracy ds. Ultradźwięków i Akustyki Podwodnej (Z57)', 'Wieloosobowe Stanowisko Pracy ds. Ultradźwięków i Akustyki Podwodnej (Z57)'), ('Laboratorium Siły i Momentu Siły (Z58)', 'Laboratorium Siły i Momentu Siły (Z58)'), ('Laboratorium Ciśnienia (Z59)', 'Laboratorium Ciśnienia (Z59)'), ('Laboratorium Informatyki Metrologicznej (Z61)', 'Laboratorium Informatyki Metrologicznej (Z61)'), ('Laboratorium Sztucznej Inteligencji (Z62)', 'Laboratorium Sztucznej Inteligencji (Z62)')], max_length=200, null=True)),
                ('zglaszajacy', models.CharField(blank=True, max_length=200, null=True)),
                ('telefon', models.CharField(blank=True, max_length=20, null=True)),
                ('nr_pomieszczenia', models.CharField(blank=True, max_length=100, null=True)),
                ('nazwa_urzadzenia', models.CharField(blank=True, max_length=200, null=True)),
                ('dostep_do_sieci', models.CharField(blank=True, choices=[('dodanie uprawnień', 'dodanie uprawnień'), ('dodanie dostępu', 'dodanie dostępu'), ('dodanie terminala', 'dodanie terminala'), ('dodanie konta', 'dodanie konta'), ('dodanie systemu', 'dodanie systemu'), ('usunięcie uprawnień', 'usunięcie uprawnień'), ('usunięcie dostępu', 'usunięcie dostępu'), ('usunięcie terminala', 'usunięcie terminala'), ('usunięcie konta', 'usunięcie konta'), ('usunięcie systemu', 'usunięcie systemu'), ('nadanie uprawnień', 'nadanie uprawnień'), ('nadanie dostępu', 'nadanie dostępu'), ('nadanie terminala', 'nadanie terminala'), ('nadanie konta', 'nadanie konta'), ('nadanie systemu', 'nadanie systemu'), ('odebranie uprawnień', 'odebranie uprawnień'), ('odebranie dostępu', 'odebranie dostępu'), ('odebranie terminala', 'odebranie terminala'), ('odebranie konta', 'odebranie konta'), ('odebranie systemu', 'odebranie systemu')], max_length=100, null=True)),
                ('nr_ewidencyjny', models.CharField(blank=True, max_length=100, null=True)),
                ('nr_gniazdka_lan', models.CharField(blank=True, max_length=100, null=True)),
                ('opis_zgloszenia', models.TextField(blank=True, null=True)),
                ('oczekiwania', models.TextField(blank=True, null=True)),
                ('istotnosc_pouf', models.CharField(blank=True, choices=[('Bardzo mała', 'Bardzo mała'), ('Mała', 'Mała'), ('Średnia', 'Średnia'), ('Duża', 'Duża'), ('Krytyczna', 'Krytyczna')], max_length=100, null=True)),
                ('istotnosc_integr', models.CharField(blank=True, choices=[('Bardzo mała', 'Bardzo mała'), ('Mała', 'Mała'), ('Średnia', 'Średnia'), ('Duża', 'Duża'), ('Krytyczna', 'Krytyczna')], max_length=100, null=True)),
                ('istotnosc_dost', models.CharField(blank=True, choices=[('Bardzo mała', 'Bardzo mała'), ('Mała', 'Mała'), ('Średnia', 'Średnia'), ('Duża', 'Duża'), ('Krytyczna', 'Krytyczna')], max_length=100, null=True)),
                ('zglaszajacy_podpis', models.CharField(blank=True, max_length=200, null=True)),
                ('kierownik_lim_opinia', models.TextField(blank=True, null=True)),
                ('kierownik_lim_podpis', models.CharField(blank=True, max_length=100, null=True)),
                ('kierownik_lim_data', models.DateField(blank=True, null=True)),
                ('kierownik_km_opinia', models.TextField(blank=True, null=True)),
                ('kierownik_km_podpis', models.CharField(blank=True, max_length=100, null=True)),
                ('kierownik_km_data', models.DateField(blank=True, null=True)),
                ('realizacja_opis', models.TextField(blank=True, null=True)),
                ('realizacja_podpis', models.CharField(blank=True, max_length=100, null=True)),
                ('realizacja_data', models.DateField(blank=True, null=True)),
                ('potwierdzenie_podpis', models.CharField(blank=True, max_length=100, null=True)),
                ('potwierdzenie_data', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OperatingSystem',
            fields=[
                ('os_type', models.CharField(db_column='Operating System', max_length=120, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('pim_id', models.AutoField(db_column='PIM ID', primary_key=True, serialize=False)),
                ('laboratorium', models.CharField(blank=True, choices=[('Laboratorium Bezpieczeństwa Ruchu Drogowego (Z11)', 'Laboratorium Bezpieczeństwa Ruchu Drogowego (Z11)'), ('Laboratorium Badań Oprogramowania (Z12)', 'Laboratorium Badań Oprogramowania (Z12)'), ('Laboratorium Temperatury (Z21)', 'Laboratorium Temperatury (Z21)'), ('Laboratorium Wilgotności (Z22)', 'Laboratorium Wilgotności (Z22)'), ('Laboratorium Analizy Gazów (Z23)', 'Laboratorium Analizy Gazów (Z23)'), ('Laboratorium Analiz Elektrochemicznych i Nieorganicznych (Z24)', 'Laboratorium Analiz Elektrochemicznych i Nieorganicznych (Z24)'), ('Laboratorium Wzorców Fizykochemicznych (Z25)', 'Laboratorium Wzorców Fizykochemicznych (Z25)'), ('Laboratorium Czasu i Częstotliwości (Z31)', 'Laboratorium Czasu i Częstotliwości (Z31)'), ('Laboratorium Długości (Z32)', 'Laboratorium Długości (Z32)'), ('Laboratorium Precyzyjnych Pomiarów Geometrycznych (Z33)', 'Laboratorium Precyzyjnych Pomiarów Geometrycznych (Z33)'), ('Laboratorium Twardości (Z34)', 'Laboratorium Twardości (Z34)'), ('Laboratorium Nowych Technologii Czasu i Długości (Z35)', 'Laboratorium Nowych Technologii Czasu i Długości (Z35)'), ('Laboratorium Wzorców Wielkości Elektrycznych DC (Z41)', 'Laboratorium Wzorców Wielkości Elektrycznych DC (Z41)'), ('Laboratorium Wzorców Wielkości Elektrycznych Małej Częstotliwości (Z42)', 'Laboratorium Wzorców Wielkości Elektrycznych Małej Częstotliwości (Z42)'), ('Laboratorium Pomiarów Elektroenergetycznych (Z43)', 'Laboratorium Pomiarów Elektroenergetycznych (Z43)'), ('Laboratorium Mikrofal, Pola Elektromagnetycznego i Kompatybilności Elektromagnetycznej (Z44)', 'Laboratorium Mikrofal, Pola Elektromagnetycznego i Kompatybilności Elektromagnetycznej (Z44)'), ('Laboratorium Wzorców Spektrofotometrycznych (Z45)', 'Laboratorium Wzorców Spektrofotometrycznych (Z45)'), ('Laboratorium Wzorców Fotometrycznych i Radiometrycznych (Z46)', 'Laboratorium Wzorców Fotometrycznych i Radiometrycznych (Z46)'), ('Wieloosobowe Stanowisko Pracy do spraw Wzorców Barwy (Z47)', 'Wieloosobowe Stanowisko Pracy do spraw Wzorców Barwy (Z47)'), ('Laboratorium Promieniowania Jonizującego (Z48)', 'Laboratorium Promieniowania Jonizującego (Z48)'), ('Laboratorium Masy (Z51)', 'Laboratorium Masy (Z51)'), ('Laboratorium Przepływów (Z53)', 'Laboratorium Przepływów (Z53)'), ('Laboratorium Akustyki (Z55)', 'Laboratorium Akustyki (Z55)'), ('Laboratorium Drgań Mechanicznych (Z56)', 'Laboratorium Drgań Mechanicznych (Z56)'), ('Wieloosobowe Stanowisko Pracy ds. Ultradźwięków i Akustyki Podwodnej (Z57)', 'Wieloosobowe Stanowisko Pracy ds. Ultradźwięków i Akustyki Podwodnej (Z57)'), ('Laboratorium Siły i Momentu Siły (Z58)', 'Laboratorium Siły i Momentu Siły (Z58)'), ('Laboratorium Ciśnienia (Z59)', 'Laboratorium Ciśnienia (Z59)'), ('Laboratorium Informatyki Metrologicznej (Z61)', 'Laboratorium Informatyki Metrologicznej (Z61)'), ('Laboratorium Sztucznej Inteligencji (Z62)', 'Laboratorium Sztucznej Inteligencji (Z62)')], db_column='Lab Name', max_length=200, null=True)),
                ('nr_pomieszczenia', models.CharField(blank=True, db_column='Room number', max_length=40, null=True)),
                ('opis', models.TextField(blank=True, db_column='Terminal Description', null=True)),
                ('numer_ewidencyjny', models.CharField(blank=True, db_column='Inventory Number', max_length=40, null=True)),
                ('typ_urzadzenia', models.CharField(blank=True, choices=[('PC', 'PC'), ('Laptop', 'Laptop'), ('Monitor', 'Monitor'), ('Air Conditioner', 'Air Conditioner'), ('Other', 'Other')], db_column='Device Type', max_length=40, null=True)),
                ('cpu', models.CharField(blank=True, db_column='CPU', max_length=40, null=True)),
                ('ram', models.CharField(blank=True, db_column='RAM', max_length=40, null=True)),
                ('pamiec_dysku', models.CharField(blank=True, db_column='Drive Memory', max_length=40, null=True)),
                ('dodatkowe_komponenty', models.TextField(blank=True, db_column='Additional Components', null=True)),
                ('oprogramowanie_specjalne', models.TextField(blank=True, db_column='Specialized Software', null=True)),
                ('konta', models.TextField(blank=True, db_column='Accounts', null=True)),
                ('data_rejestracji', models.DateField(auto_now=True, db_column='Date of Registry', null=True)),
                ('nr_gniazda', models.CharField(blank=True, db_column='Socket Number', max_length=40, null=True)),
                ('typ_gniazd', models.CharField(blank=True, db_column='Socket Type', max_length=120, null=True)),
                ('opiekun_1', models.CharField(db_column='Supervisor 1', max_length=40, null=True)),
                ('opiekun_2', models.CharField(blank=True, db_column='Supervisor 2', max_length=40, null=True)),
                ('typ_polaczenia_sieciowego', models.CharField(blank=True, choices=[('Office', 'Office'), ('OT', 'OT'), ('Isolated', 'Isolated'), ('None', 'None')], db_column='Terminal Connection Type', max_length=40, null=True)),
                ('system_operacyjny', models.ManyToManyField(blank=True, db_column='Operating System', null=True, to='myapp.operatingsystem')),
            ],
        ),
    ]
