# Generated by Django 5.0.7 on 2024-07-19 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_zgloszenia', models.CharField(max_length=100)),
                ('data_zgloszenia', models.DateField()),
                ('nazwa_zakladu', models.CharField(max_length=200)),
                ('laboratorium', models.CharField(max_length=200)),
                ('zglaszajacy', models.CharField(max_length=200)),
                ('telefon', models.CharField(max_length=20)),
                ('nr_pomieszczenia', models.CharField(max_length=100)),
                ('nazwa_urzadzenia', models.CharField(max_length=200)),
                ('dostep_do_sieci', models.BooleanField()),
                ('nr_ewidencyjny', models.CharField(max_length=100)),
                ('nr_gniazdka_lan', models.CharField(max_length=100)),
                ('opis_zgloszenia', models.TextField()),
                ('oczekiwania', models.TextField()),
                ('istotnosc_pouf', models.CharField(max_length=100)),
                ('istotnosc_integr', models.CharField(max_length=100)),
                ('istotnosc_dost', models.CharField(max_length=100)),
                ('kierownik_lim_opinia', models.TextField()),
                ('kierownik_lim_podpis', models.CharField(max_length=100)),
                ('kierownik_lim_data', models.DateField()),
                ('kierownik_km_opinia', models.TextField()),
                ('kierownik_km_podpis', models.CharField(max_length=100)),
                ('kierownik_km_data', models.DateField()),
                ('realizacja_opis', models.TextField()),
                ('realizacja_podpis', models.CharField(max_length=100)),
                ('realizacja_data', models.DateField()),
                ('potwierdzenie_podpis', models.CharField(max_length=100)),
                ('potwierdzenie_data', models.DateField()),
            ],
        ),
    ]
