# Generated by Django 5.0.7 on 2024-07-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdata',
            name='data_zgloszenia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='dostep_do_sieci',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='istotnosc_dost',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='istotnosc_integr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='istotnosc_pouf',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='kierownik_km_data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='kierownik_km_opinia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='kierownik_km_podpis',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='kierownik_lim_data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='kierownik_lim_opinia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='kierownik_lim_podpis',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='laboratorium',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='nazwa_urzadzenia',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='nazwa_zakladu',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='nr_ewidencyjny',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='nr_gniazdka_lan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='nr_pomieszczenia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='nr_zgloszenia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='oczekiwania',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='opis_zgloszenia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='potwierdzenie_data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='potwierdzenie_podpis',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='realizacja_data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='realizacja_opis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='realizacja_podpis',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='telefon',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='zglaszajacy',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
