# Generated by Django 5.0.7 on 2024-07-22 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_formdata_data_zgloszenia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdata',
            name='dostep_do_sieci',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
