# Generated by Django 5.0.7 on 2024-07-22 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_formdata_dostep_do_sieci'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdata',
            name='zglaszajacy_podpis',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
