# Generated by Django 5.0.7 on 2024-07-22 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_formdata_zglaszajacy_podpis'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdata',
            name='nr_EZD',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
