# Generated by Django 5.0.7 on 2024-07-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_formdata_nr_ezd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdata',
            name='dostep_do_sieci',
            field=models.CharField(blank=True, choices=[('green', 'green'), ('red', 'red')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='istotnosc_dost',
            field=models.CharField(blank=True, choices=[('Bardzo mała', 'Bardzo mała'), ('Mała', 'Mała'), ('Średnia', 'Średnia'), ('Duża', 'Duża'), ('Krytyczna', 'Krytyczna')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='istotnosc_integr',
            field=models.CharField(blank=True, choices=[('Bardzo mała', 'Bardzo mała'), ('Mała', 'Mała'), ('Średnia', 'Średnia'), ('Duża', 'Duża'), ('Krytyczna', 'Krytyczna')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='istotnosc_pouf',
            field=models.CharField(blank=True, choices=[('Bardzo mała', 'Bardzo mała'), ('Mała', 'Mała'), ('Średnia', 'Średnia'), ('Duża', 'Duża'), ('Krytyczna', 'Krytyczna')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='laboratorium',
            field=models.CharField(blank=True, choices=[('green', 'green'), ('red', 'red')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='nazwa_zakladu',
            field=models.CharField(blank=True, choices=[('green', 'green'), ('red', 'red')], max_length=200, null=True),
        ),
    ]
