# Generated by Django 5.0.7 on 2024-07-22 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_formdata_dostep_do_sieci_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdata',
            name='dostep_do_sieci',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='laboratorium',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
