from django.db import models

class FormData(models.Model):
    nr_zgloszenia = models.CharField(max_length=100, blank=True, null=True)
    nr_EZD = models.CharField(max_length=100, blank=True, null=True)
    data_zgloszenia = models.DateField(blank=True, null=True)
    nazwa_zakladu = models.CharField(max_length=200, blank=True, null=True, choices=[('green', 'green'), ('red', 'red')])
    laboratorium = models.CharField(max_length=200, blank=True, null=True, choices=[('green', 'green'), ('red', 'red')])
    zglaszajacy = models.CharField(max_length=200, blank=True, null=True)
    telefon = models.CharField(max_length=20, blank=True, null=True)
    nr_pomieszczenia = models.CharField(max_length=100, blank=True, null=True)
    nazwa_urzadzenia = models.CharField(max_length=200, blank=True, null=True)
    dostep_do_sieci = models.CharField(max_length=100, blank=True, null=True, choices=[('dodanie uprawnień', 'dodanie uprawnień'), ('dodanie dostępu', 'dodanie dostępu'), ('dodanie terminala', 'dodanie terminala'), ('dodanie konta', 'dodanie konta'), ('dodanie systemu', 'dodanie systemu'), ('usunięcie uprawnień', 'usunięcie uprawnień'), ('usunięcie dostępu', 'usunięcie dostępu'), ('usunięcie terminala', 'usunięcie terminala'), ('usunięcie konta', 'usunięcie konta'), ('usunięcie systemu', 'usunięcie systemu'), ('nadanie uprawnień', 'nadanie uprawnień'), ('nadanie dostępu', 'nadanie dostępu'), ('nadanie terminala', 'nadanie terminala'), ('nadanie konta', 'nadanie konta'), ('nadanie systemu', 'nadanie systemu'), ('odebranie uprawnień', 'odebranie uprawnień'), ('odebranie dostępu', 'odebranie dostępu'), ('odebranie terminala', 'odebranie terminala'), ('odebranie konta', 'odebranie konta'), ('odebranie systemu', 'odebranie systemu'), ])
    nr_ewidencyjny = models.CharField(max_length=100, blank=True, null=True)
    nr_gniazdka_lan = models.CharField(max_length=100, blank=True, null=True)
    opis_zgloszenia = models.TextField(blank=True, null=True)
    oczekiwania = models.TextField(blank=True, null=True)
    istotnosc_pouf = models.CharField(max_length=100, blank=True, null=True, choices=[('Bardzo mała', 'Bardzo mała'), ('Mała', 'Mała'),('Średnia', 'Średnia'),('Duża', 'Duża'),('Krytyczna', 'Krytyczna')])
    istotnosc_integr = models.CharField(max_length=100, blank=True, null=True, choices=[('Bardzo mała', 'Bardzo mała'), ('Mała', 'Mała'),('Średnia', 'Średnia'),('Duża', 'Duża'),('Krytyczna', 'Krytyczna')])
    istotnosc_dost = models.CharField(max_length=100, blank=True, null=True, choices=[('Bardzo mała', 'Bardzo mała'), ('Mała', 'Mała'),('Średnia', 'Średnia'),('Duża', 'Duża'),('Krytyczna', 'Krytyczna')])
    zglaszajacy_podpis = models.CharField(max_length=200, blank=True, null=True)
    kierownik_lim_opinia = models.TextField(blank=True, null=True)
    kierownik_lim_podpis = models.CharField(max_length=100, blank=True, null=True)
    kierownik_lim_data = models.DateField(blank=True, null=True)
    kierownik_km_opinia = models.TextField(blank=True, null=True)
    kierownik_km_podpis = models.CharField(max_length=100, blank=True, null=True)
    kierownik_km_data = models.DateField(blank=True, null=True)
    realizacja_opis = models.TextField(blank=True, null=True)
    realizacja_podpis = models.CharField(max_length=100, blank=True, null=True)
    realizacja_data = models.DateField(blank=True, null=True)
    potwierdzenie_podpis = models.CharField(max_length=100, blank=True, null=True)
    potwierdzenie_data = models.DateField(blank=True, null=True)

    def __str__(self):
        return self.nr_zgloszenia if self.nr_zgloszenia else 'No ID'
